### ISSUE TITLE
After doing an incrememntal upgrade from DNN v5 - v7.4, and upgrading the Quiz mod from v3 to v6, the cert #'s are wrong

### ISSUE THREAD

**Issue by michaeldoxsey** [mitchelsellers/icg.dnn.quiz#3]
Since upgrading a client site to version 7 of DNN, and upgrading the Quiz module to v6, when you first see the certificate it shows a very low number - like the counter reset itself (shows like, 1, 2, 3, 4)

But when you go back in and click on "Completion Certificate" however, the cert number is accurate.

**Comment by mitchelsellers** [comment]
That is a very unusual experience.  That shouldn't be the case.

I tried to re-create it and haven't been able to yet, but will look more later this week.

**Comment by mitchelsellers** [comment]
Re-tested this issue on the current build, cannot recreate
